### ISSUE TITLE
Post processor macro causes errors when run with freecad 1.1

### ISSUE THREAD

**Issue by BeptoBepis** [MillenniumMachines/MillenniumOS#225]
Issue occurred immediately after updating to freecad1.1

Lines 831 and 836 of the millennium_os_post.py file reference 'tool.shapename' which throws an error for: 
" 'FeaturePython' object has no attribute 'ShapeName' "

This is due to the object actually being named 'Shape' rather than 'ShapeName' in freecad tool definition files. 

Issue can be fixed by changing 'tc.Tool.ShapeName' to 'tc.Tool.Shape' on lines 831 and 836

**Comment by benagricola** [comment]
Hi @BeptoBepis there was a recent PR for compatibility with FreeCAD _1.2_ which changed the behaviour of this code:

https://github.com/MillenniumMachines/MillenniumOS/pull/223/changes

Can you apply this and see if it works on 1.1 as well? It sounds like there might have been some flipflopping with the name between 1.0, 1.1 and 1.2. We haven't made a release since that PR was applied so it would be a real help to test if that also works for 1.1.
